import {
  ace,
  alpaca,
  ascendex,
  bequant,
  bigone,
  binance,
  binancecoinm,
  binanceus,
  binanceusdm,
  bingx,
  bit2c,
  bitbank,
  bitbns,
  bitcoincom,
  bitfinex,
  bitfinex1,
  bitflyer,
  bitget,
  bithumb,
  bitmart,
  bitmex,
  bitopro,
  bitpanda,
  bitrue,
  bitso,
  bitstamp,
  bitteam,
  bitvavo,
  bl3p,
  blockchaincom,
  blofin,
  btcalpha,
  btcbox,
  btcmarkets,
  btcturk,
  bybit,
  cex,
  coinbase,
  coinbaseadvanced,
  coinbaseexchange,
  coinbaseinternational,
  coincatch,
  coincheck,
  coinex,
  coinlist,
  coinmate,
  coinmetro,
  coinone,
  coinsph,
  coinspot,
  cryptocom,
  defx,
  delta,
  deribit,
  digifinex,
  ellipx,
  exmo,
  fmfwio,
  gate,
  gateio,
  gemini,
  hashkey,
  hitbtc,
  hollaex,
  htx,
  huobi,
  huobijp,
  hyperliquid,
  idex,
  independentreserve,
  indodax,
  kraken,
  krakenfutures,
  kucoin,
  kucoinfutures,
  kuna,
  latoken,
  lbank,
  luno,
  mercado,
  mexc,
  myokx,
  ndax,
  novadax,
  oceanex,
  okcoin,
  okx,
  onetrading,
  oxfun,
  p2b,
  paradex,
  paymium,
  phemex,
  poloniex,
  poloniexfutures,
  probit,
  timex,
  tokocrypto,
  tradeogre,
  upbit,
  vertex,
  wavesexchange,
  whitebit,
  woo,
  woofipro,
  xt,
  yobit,
  zaif,
  zonda,
} from 'ccxt'

// Because CCXT doesn't export this correctly.
const exchanges = {
  ace: ace,
  alpaca: alpaca,
  ascendex: ascendex,
  bequant: bequant,
  bigone: bigone,
  binance: binance,
  binancecoinm: binancecoinm,
  binanceus: binanceus,
  binanceusdm: binanceusdm,
  bingx: bingx,
  bit2c: bit2c,
  bitbank: bitbank,
  bitbns: bitbns,
  bitcoincom: bitcoincom,
  bitfinex: bitfinex,
  bitfinex1: bitfinex1,
  bitflyer: bitflyer,
  bitget: bitget,
  bithumb: bithumb,
  bitmart: bitmart,
  bitmex: bitmex,
  bitopro: bitopro,
  bitpanda: bitpanda,
  bitrue: bitrue,
  bitso: bitso,
  bitstamp: bitstamp,
  bitteam: bitteam,
  bitvavo: bitvavo,
  bl3p: bl3p,
  blockchaincom: blockchaincom,
  blofin: blofin,
  btcalpha: btcalpha,
  btcbox: btcbox,
  btcmarkets: btcmarkets,
  btcturk: btcturk,
  bybit: bybit,
  cex: cex,
  coinbase: coinbase,
  coinbaseadvanced: coinbaseadvanced,
  coinbaseexchange: coinbaseexchange,
  coinbaseinternational: coinbaseinternational,
  coincatch: coincatch,
  coincheck: coincheck,
  coinex: coinex,
  coinlist: coinlist,
  coinmate: coinmate,
  coinmetro: coinmetro,
  coinone: coinone,
  coinsph: coinsph,
  coinspot: coinspot,
  cryptocom: cryptocom,
  defx: defx,
  delta: delta,
  deribit: deribit,
  digifinex: digifinex,
  ellipx: ellipx,
  exmo: exmo,
  fmfwio: fmfwio,
  gate: gate,
  gateio: gateio,
  gemini: gemini,
  hashkey: hashkey,
  hitbtc: hitbtc,
  hollaex: hollaex,
  htx: htx,
  huobi: huobi,
  huobijp: huobijp,
  hyperliquid: hyperliquid,
  idex: idex,
  independentreserve: independentreserve,
  indodax: indodax,
  kraken: kraken,
  krakenfutures: krakenfutures,
  kucoin: kucoin,
  kucoinfutures: kucoinfutures,
  kuna: kuna,
  latoken: latoken,
  lbank: lbank,
  luno: luno,
  mercado: mercado,
  mexc: mexc,
  myokx: myokx,
  ndax: ndax,
  novadax: novadax,
  oceanex: oceanex,
  okcoin: okcoin,
  okx: okx,
  onetrading: onetrading,
  oxfun: oxfun,
  p2b: p2b,
  paradex: paradex,
  paymium: paymium,
  phemex: phemex,
  poloniex: poloniex,
  poloniexfutures: poloniexfutures,
  probit: probit,
  timex: timex,
  tokocrypto: tokocrypto,
  tradeogre: tradeogre,
  upbit: upbit,
  vertex: vertex,
  wavesexchange: wavesexchange,
  whitebit: whitebit,
  woo: woo,
  woofipro: woofipro,
  xt: xt,
  yobit: yobit,
  zaif: zaif,
  zonda: zonda,
}

export type Exchanges = typeof exchanges
