import { Schema } from 'effect'
import { BacktestParametersSchema } from './BacktestParameters'
import { BacktestStateSchema } from './BacktestState'

/**
 * Schema for process signals input
 */
export const ProcessSignalsInputSchema = Schema.Struct({
  /** Signals generated by the strategy */
  signals: Schema.Array(Schema.Any), // We'll validate this separately

  /** Historical price data */
  candlesticks: Schema.Array(Schema.Any), // We'll validate this separately

  /** Backtest configuration parameters */
  parameters: BacktestParametersSchema,

  /** Initial backtest state */
  initialState: BacktestStateSchema,
})

/**
 * Type for process signals input
 */
export type ProcessSignalsInput = Schema.Schema.Type<
  typeof ProcessSignalsInputSchema
>
