[project]
name = "homebankimport"
version = "2024.0.0"
description = "homebankimport"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }
keywords = ["Artificial Intelligence", "Machine Learning"]
authors = [{ email = "tom.wieland@gmail.com" }, { name = "Tom Wieland" }]
maintainers = [{ name = "Tom Wieland", email = "tom.wieland@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
]
dependencies = [
  "black>23.3.0",
  "debugpy>1.6.7",
  "flake8>6.0.0",
  "isort>5.12.0",
  # "pylance>0.9.8",

  "pytest",
  "pytest-cov",
  "pytest-html",

  "pandas",
  "python-dotenv",
]

[tool.coverage.run]
branch = true
source = ["homebankimport"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/applications/homebankimport/html' --cov-report xml:'../../coverage/applications/homebankimport/coverage.xml' --html='../../reports/applications/homebankimport/unittests/html/index.html' --junitxml='../../reports/applications/homebankimport/unittests/junit.xml'"

[tool.poetry]
name = "homebankimport"
version = "1.0.0"
description = "Automatically generated by Nx."
authors = []
license = 'Proprietary'
readme = 'README.md'

[[tool.poetry.packages]]
include = "homebankimport"

[tool.poetry.dependencies]
# python = ">=3.8.1,<3.11"
python = ">=3.9,<3.13"
pyautogen = "0.2.13"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "8.0.0"
pytest-sugar = "1.0.0"
pytest-cov = "4.1.0"
pytest-html = "4.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.nx]
autoActivate = true
