// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type GetUserByNameArgs = {
  readonly "name": string;
};

export type GetUserByNameReturns = Array<{
  "name": string;
}>;

export function getUserByName(client: Executor, args: GetUserByNameArgs): Promise<GetUserByNameReturns> {
  return client.query(`\
select User {
  name
}

filter .name = <str>$name;`, args);

}
