[package]
name = "code9-test-rust-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.7.7"
cargo-shuttle = "0.48.3"
shuttle-axum = "0.48.0"
shuttle-runtime = "0.48.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
