---
name: Nix Flake actions
# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  devenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: DevEnv / Install
        run: nix profile install nixpkgs#devenv
      - name: DevEnv / Test
        run: devenv test
