name: Leptos Shuttle API

on:
  push:
    paths:
      - 'applications/test-rust-api/**'
      - '.github/workflows/leptos-shuttle-api.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Nix Install
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix Cachix Install
        uses: cachix/cachix-action@v14
        with:
          name: skeleton1nodejs0test1leptos
          # # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check
        working-directory: applications/test-rust-api
        run: |
          nix develop .#ci --command bin/check

      - name: Build
        working-directory: applications/test-rust-api
        run: |
          nix develop .#ci --command bin/build

      - name: Deploy
        working-directory: applications/test-rust-api
        env:
          SHUTTLE_API_KEY: '${{ secrets.SHUTTLE_API_KEY }}'
        # run: bin/deploy
        run: |
          nix develop .#ci --command bin/deploy