name: Leptos Shuttle API

on:
  push:
    paths:
      - 'applications/test-rust-api/**'
      - '.github/workflows/leptos-shuttle-api.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Nix Install
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix Cachix Install
        uses: cachix/cachix-action@v14
        with:
          name: skeleton1nodejs0test1leptos
          # # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Test
        working-directory: applications/test-leptos
        run: nix --extra-experimental-features 'nix-command flakes' flake check

      - name: Build
        working-directory: applications/test-leptos
        run: nix build --extra-experimental-features 'nix-command flakes' .#default

      - name: Deploy
        working-directory: applications/test-leptos
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: |
          # Replace with the actual shuttle-cli command
          cargo shuttle deploy result