name: Deploy to Shuttle.rs

on:
  push:
    paths:
      - 'applications/test-leptos/**'
      - '.github/workflows/leptos-shuttle-app.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: https://nixos.org/nix/install

      - name: Install Cachix CLI
        run: nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install

      - name: Add Nix store to PATH
        run: |
          echo "$(dirname $(which cachix))" >> $GITHUB_PATH

      - name: Verify Cachix Installation
        run: cachix --version

      # - name: Set up Cachix
      #   if: success()
      #   uses: cachix/cachix-action@v10
      #   with:
      #     name: your-cachix-cache-name
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Cache Nix Store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-nix-store-

      - name: Build with Nix Flake
        working-directory: applications/test-leptos
        run: nix build --extra-experimental-features 'nix-command flakes' .#default

      - name: Deploy to Shuttle.rs
        working-directory: applications/test-leptos
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: |
          # Replace with the actual shuttle-cli command
          cargo shuttle deploy result