import { HumanMessage, SystemMessage } from '@langchain/core/messages'
import { Ollama } from '@langchain/ollama'

const model = new Ollama({
  baseUrl: 'http://0.0.0.0:11434',
  model: 'llama3.2:latest',
})

const systemMessage = new SystemMessage(`
  You are a summarization AI specializing in summarizing text.
`)

const humanMessage = new HumanMessage(`
  Please summarize the following text, ensuring it is concise and to the point.
  Respond in a manner that a 5 year old could understand.

  Text:
  Massive stars (M>∗8M⊙) play a pivotal role in shaping their galactic surroundings due to their high luminosity and intense ionizing radiation. However, the precise mechanisms governing the formation of massive stars remain elusive. Complex organic molecules (COMs) offer an avenue for studying star formation across the low- to high-mass spectrum because COMs are found in every young stellar object (YSO) phase and offer insight into the structure and temperature. We aim to unveil patterns in the evolution of COM chemistry in 41 massive young stellar objects (MYSOs) sourced from diverse catalogues, using Atacama Large Millimeter/Submillimeter Array Band 6 spectra. Previous line analysis of these sources has shown the presence of methanol, methyl acetylene, and methyl cyanide with diverse excitation temperatures (a few tens to hundreds of Kelvin) and column densities (spanning two to four orders of magnitude in range), indicating a possible evolutionary path across sources. However, this analysis usually involves manual line extraction and rotational diagram fitting. Here, we improve upon this process by directly retrieving the physicochemical state of MYSOs from their dimensionally-reduced spectra. We use a Locally Linear Embedding to find a lower-dimensional projection for the physicochemical parameters obtained from individual line analysis. We identify clusters of similar MYSOs in this embedded space using a Gaussian Mixture Model. We find three groups of MYSOs corresponding to distinct physicochemical conditions: i) cold, COM-poor sources, ii) warm, medium-COM-abundance sources, and iii) hot, COM-rich sources. We then use principal component analysis (PCA) on the source spectra to obtain eigenspectra components, finding further evidence for an evolutionary path across MYSO groups. Finally, we find that the physicochemical state of MYSOs in our sample can be derived directly from the spectra by training a simple random forest model on the first few spectral PCA components. Our results highlight the effectiveness of dimensionality reduction in obtaining clear physical insights directly from MYSO spectra.
  Key Words.: methods: data analysis – astrochemistry – stars: formation – ISM: clouds – stars: protostars – radio lines: stars
  1 Introduction

  Giant molecular clouds (GMC) are dense and cold agglomerations of gas (mainly molecular hydrogen) and dust in the interstellar medium (ISM) and are the sites of star formation (Carroll & Ostlie, 2017). GMCs fragment hierarchically via gravitational collapse into smaller and denser clumps with masses between 103−105 M⊙, and temperatures of 10−20 K (van den Ancker, 1999; Williams et al., 2000), for example, see a cartoon with the evolutionary stages of high-mass star formation in Fig. 1. The clumps continue to collapse under the influence of their gravity into denser protostellar cores where the formation of massive young stellar objects (MYSOs) and multiple stellar systems begins (see the review from Williams et al., 2000, and references therein). The massive cold collapsing cores can become infrared dark clouds (IRDCs), hot molecular cores (HMCs), and H ii regions (Kurtz et al., 2000; Kurtz, 2005; Menten et al., 2005; Hoare et al., 2007). Late star-forming stages (from ∼104 years, Fig. 1) are traced by the emergence of outflows, jets, bright infrared (IR) sources, masers of methanol and water, and compact H ii regions, (see e.g. Hoare et al., 2007; Kurtz, 2005; Menten, 1991; Shepherd & Churchwell, 1996). However, clumps and cold cores (the early stages on the left side of Fig. 1) do not have those signatures already present, which makes them more challenging to study.
  Refer to caption
  Figure 1: Evolutionary stages of high-mass star formation. Cartoon credit: Dr. Cormac R. Purcell.

  Complex organic molecules (COMs) are observed in different evolutionary stages of high-mass star formation (Herbst & van Dishoeck, 2009). COMs offer unique insight into the physical and chemical structure of the core at the earliest stages of massive star formation. Therefore, studying their formation and evolution is fundamental for understanding the high-mass star formation process. In particular, IRDCs are filamentary structures containing cold (T<100 K), massive cores (10 M⊙ to 2×103 M⊙) where stars are forming and the first generation of molecular species–the precursors of COMs–is formed in the ice mantles via surface chemistry. Due to their size, density, and mass similarities with HMCs, IRDCs are considered an earlier evolutionary phase of HMCs (Rathborne et al., 2006). On the other hand, HMCs are compact (<0.1 pc), warm (T>100 K), and dense (n>106 cm-3) sources with an elevated abundance of complex molecules at small spatial scales proposed to be driven by ice sublimation (e.g. see Millar, 1996, and references therein).

  COMs such as \chCH3OH (methanol), \chCH3CN (methyl cyanide), and \chCH3CCH (methyl acetylene) are essential in tracing the evolution of hot cores and cold extended structures (Isokoski et al., 2013; Bisschop et al., 2007; Öberg et al., 2014). For instance, Fayolle et al. (2015) studied MYSOs with weak hot organic emission lines, finding that N-bearing molecules are generally concentrated in the cores while O- and C-bearing molecules are present both in the cores and the envelopes. Nevertheless, larger surveys of MYSOs with ice detections are needed to quantify the impact of the initial conditions on COM formation. Observations at high sensitivity, spatial, and spectral resolution from the Atacama Large Millimeter/Sub-Millimeter Array (ALMA) (e.g. see Avison et al., 2023) are detecting COM emission from regions that are usually optically thick at most frequencies. Frimpong (2021) performed an extended and exhaustive analysis of a large spectral sample of MYSOs observed by Avison et al. (2023). Among all molecules studied by Frimpong (2021), species such as \chCH3OH, \chCH3CN, and \chCH3CCH efficiently describe the physical and chemical conditions of the sources, showing two distinct evolutionary stages and hinting at a possible third intermediate stage. These results thus open new possibilities for spectral MYSO classification. However, the analysis and interpretation of large samples of chemically rich spectra demands considerable effort and time due to the wide variety of species present and the inherent heterogeneity of the physical conditions.

  Classification methods for young stellar object (YSO) spectra have been successfully implemented along with simulations and observations (Singh et al., 1998; Ronen et al., 1999; Yip et al., 2004; Ward & Lumsden, 2016). For instance, Ward & Lumsden (2016) demonstrated the potential of dimensionality reduction techniques, such as locally linear embedding (LLE) and principal component analysis (PCA), to efficiently classify large spectral samples based on the presence/absence of emission lines. In this work, we build on this basic idea and show that dimensionality reduction techniques are also robust and helpful in studying chemical evolution in large samples of MYSO spectra. We find that the first eight PCA components of the original spectra retain sufficient physicochemical information to classify the sources comparably to methods based on molecular excitation temperature and column density obtained from manual line extraction and rotational diagram fitting. Thus, reduced-dimensionality spectra can convey information about a source’s chemical evolutionary stage, which is particularly useful in distinguishing between COM-rich and COM-poor sources. This blind, PCA-based approach to source classification is more efficient than the traditional rotational diagram fitting method in terms of human pre-processing time, as it requires little individual source or line inspection and extraction.

  Section 2 presents the list of MYSOs, between HMCs and IRDCs, selected for our study and observed by ALMA. Section 3 details the dimensionality reduction and classification methods. Our results are outlined in Sect. 4. We discuss the implications of our results in Sect. 5 and summarise our work in Sect. 6.
`)

const stream = await model.stream([systemMessage, humanMessage])

let output = ''
for await (const chunk of stream) {
  output += chunk
}

console.log(output)
